// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  button: dynamic(() => import("./Button")),
  hero: dynamic(() => import("./Hero")),
  teaser: dynamic(() => import("./Teaser")),
  text_image_combo: dynamic(() => import("./TextImageCombo")),
};
